# Generated by Django 6.0.6 on 2026-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_debts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('years', models.IntegerField()),
                ('annual_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_hoa', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
